apiVersion: apps/v1
kind: Deployment
metadata: 
  name: front-end-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-service
  template:
    metadata: 
      labels:
        app: front-end-service
    spec:
      containers:
      - name: front-end-service
        image: damianvu/front-end-service:1.0.3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "126Mi"
            cpu: "500m"
        env:
          - name: BROKER_URL
            value: "http://broker-service.info"
        ports:
          - containerPort: 8081
        
---

apiVersion: v1
kind: Service
metadata: 
  name: front-end-service
spec:
  selector:
    app: front-end-service
  ports:
    - protocol: TCP
      name: main-port
      port: 8081
      targetPort: 8081